name: Tests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  tests:
    runs-on: ubuntu-18.04
    env:
      GOPATH: ${{ github.workspace }}
    steps:
    - name: Set up Go 1.10
      uses: actions/setup-go@v1
      with:
        go-version: 1.10.x
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        path: ${{ github.workspace }}/src/github.com/canonical/go-sp800.90a-drbg
    - name: Install govendor
      run: go get -u github.com/kardianos/govendor
    - name: Cache Go dependencies
      id: cache-go-govendor
      uses: actions/cache@v1
      with:
        path: ${{ github.workspace }}/.cache/govendor
        key: go-govendor-{{ hashFiles('**/vendor.json') }}
    - name: Get Go dependencies
      run: cd ${{ github.workspace }}/src/github.com/canonical/go-sp800.90a-drbg && ${{ github.workspace }}/bin/govendor sync
    - name: Build
      run: go build -v github.com/canonical/go-sp800.90a-drbg/...
    - name: Test
      run: go test -v github.com/canonical/go-sp800.90a-drbg/...
    - name: Go vet
      run: go vet github.com/canonical/go-sp800.90a-drbg/...
